name: Sync Fork

on:
  schedule:
    - cron: '0 6 * * *' # 6am UTC
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          base: main
          head: main
